In [3]:
import numpy as np

In [6]:
a = np.array([[ 0,  1,  2,  3], 
              [ 4,  5,  6,  7],
              [ 8,  9, 10, 11]])
a


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
#raval()
b=a.ravel()
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [11]:
b[3]=100
b

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [13]:
a
#在ravel()做元素變更會影響原陣列的元素值

array([[  0,   1,   2, 100],
       [  4,   5,   6,   7],
       [  8,   9,  10,  11]])

In [14]:
#order='C/F' #C/F以ROW/COLUMN為主的順序展開
a.ravel(order='C')

array([  0,   1,   2, 100,   4,   5,   6,   7,   8,   9,  10,  11])

In [15]:
a.ravel(order='F')

array([  0,   4,   8,   1,   5,   9,   2,   6,  10, 100,   7,  11])

In [16]:
#np.reshape(a, new_shape)
#a.reshape(new_shape, refcheck=True)
a=np.arange(15)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [17]:
a.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [18]:
a.size
#a.reshape(18)會出錯因為shape總數只有15

15

In [19]:
a.reshape((5,-1)) #-1為模糊指定由numpy計算

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [21]:
b=a.reshape((3,5))
b[0,2]=100
b

array([[  0,   1, 100,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [22]:
a

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14])

In [23]:
#np.resize(a, new_shape)
#a.resize(new_shape, refcheck=True) 
#要改變被 reference 的陣列時有可能會產生錯誤，這時候可以將 refcheck 引數設為 False
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [25]:
b.resize((3,6),refcheck=False)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14,  0,  0,  0]])

In [27]:
a = np.array([[[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]],
              [[1, 2, 3], [4, 5, 6],
              [7, 8, 9], [10, 11, 12]]])
a
#shape:(2,4,3)

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [28]:
a.sum(axis=0)
#沿軸對元素做加總

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [30]:
#np.newaxis增加新維度
a = np.arange(12).reshape(2, 6)
a.shape

(2, 6)

In [31]:
a[:,np.newaxis,:].shape

(2, 1, 6)

In [35]:
a = np.arange(10).reshape(5, 2)
b = np.arange(6).reshape(3, 2)
#以axis=0合併
np.concatenate((a, b))


array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9],
       [0, 1],
       [2, 3],
       [4, 5]])

In [36]:
#以y-axis做合併
c=np.arange(10).reshape(5,2)
np.stack((a,c),axis=1)

array([[[0, 1],
        [0, 1]],

       [[2, 3],
        [2, 3]],

       [[4, 5],
        [4, 5]],

       [[6, 7],
        [6, 7]],

       [[8, 9],
        [8, 9]]])

In [39]:
#根據水平軸進行合併
np.hstack((a, c))

array([[0, 1, 0, 1],
       [2, 3, 2, 3],
       [4, 5, 4, 5],
       [6, 7, 6, 7],
       [8, 9, 8, 9]])

In [40]:
b=np.arange(30).reshape(5,6)
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [44]:
# 依水平軸去做等分分割
np.hsplit(b,3)

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27]]),
 array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29]])]

In [45]:
np.hsplit(b, [2, 3, 5])

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25]]),
 array([[ 2],
        [ 8],
        [14],
        [20],
        [26]]),
 array([[ 3,  4],
        [ 9, 10],
        [15, 16],
        [21, 22],
        [27, 28]]),
 array([[ 5],
        [11],
        [17],
        [23],
        [29]])]

In [46]:
# 依垂直軸按照區段去分割，超出的區段則傳回空陣列
np.vsplit(b, [2, 4, 6])


[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[24, 25, 26, 27, 28, 29]]),
 array([], shape=(0, 6), dtype=int32)]

In [47]:
a=np.arange(5)
for i in a:
    print(i)

0
1
2
3
4


In [48]:
#多維陣列的迭代則以 axis 0 為準
b = np.arange(6).reshape(2, 3)
b

array([[0, 1, 2],
       [3, 4, 5]])

In [49]:
for i in b:
    print(i)

[0 1 2]
[3 4 5]


In [50]:
#列出多維陣列所有元素的話
for i in b.flat:
    print(i)

0
1
2
3
4
5


In [51]:
a = np.random.randint(1, 20, 10)
a

array([ 9,  4, 15, 18,  7,  7,  7, 14, 15, 15])

In [52]:
b=a.reshape(2,5)
b

array([[ 9,  4, 15, 18,  7],
       [ 7,  7, 14, 15, 15]])

In [54]:
#keepdims=True，結果會保留原陣列的維度來顯示。
np.amax(b,keepdims=True)

array([[18]])

In [55]:
# 列出各 row 最大值
b.max(axis=1)

array([18, 15])

In [56]:
np.amax(b, axis=1)

array([18, 15])

In [57]:
b.min(axis=0)

array([ 7,  4, 14, 15,  7])

In [59]:
#顯示最大值和最小值的索引：argmax() 與 argmin()
np.random.seed(0)
a = np.random.randint(1, 20, size=(3, 4))
a

array([[13, 16,  1,  4],
       [ 4,  8, 10, 19],
       [ 5,  7, 13,  2]])

In [60]:
np.argmax(a, axis=0)

array([0, 0, 2, 1], dtype=int64)

In [61]:
#numpy.where(condition[, x, y])
np.where(a>10)
#顯示的維度位置要合著一起看

(array([0, 0, 1, 2], dtype=int64), array([0, 1, 3, 2], dtype=int64))

In [62]:
np.where(a > 10, "Y", "N")

array([['Y', 'Y', 'N', 'N'],
       ['N', 'N', 'N', 'Y'],
       ['N', 'N', 'Y', 'N']], dtype='<U1')

In [64]:
#numpy.nonzero(array) = np.where(array!=0)
np.random.seed(2)
a = np.random.randint(0, 5, 10)
a

array([0, 0, 3, 2, 3, 0, 2, 1, 3, 2])

In [66]:
a.nonzero()

(array([2, 3, 4, 6, 7, 8, 9], dtype=int64),)

In [67]:
#sort(),argsort()
np.random.seed(3)
a = np.random.randint(0, 20, 10)
np.sort(a)

array([ 0,  3,  6,  8,  9, 10, 10, 10, 11, 19])

In [69]:
np.argsort(a)

array([3, 1, 9, 2, 7, 0, 5, 8, 6, 4], dtype=int64)

In [70]:
b = np.random.randint(0, 20, size=(5, 4))
b

array([[ 0, 12,  7, 14],
       [17,  2,  2,  1],
       [19,  5,  8, 14],
       [ 1, 10,  7, 11],
       [ 1, 15, 16,  5]])

In [71]:
np.sort(b,axis=0)
#kind可分各種排序演算法，eg.kind="heapsort"

array([[ 0,  2,  2,  1],
       [ 1,  5,  7,  5],
       [ 1, 10,  7, 11],
       [17, 12,  8, 14],
       [19, 15, 16, 14]])