In [1]:
import numpy as np

In [6]:
#1.有多少學生英文成績比數學成績高?
np.greater(np.array([55,89,76,65,48,70]),np.array([60,85,60,68,55,60]))
#3位

array([False,  True,  True, False, False,  True])

In [8]:
#2.是否全班同學最高分都是國文?
np.greater(np.array([65,90,82,72,66,77]),np.array([55,89,76,65,48,70]))


array([ True,  True,  True,  True,  True,  True])

In [9]:
np.greater(np.array([65,90,82,72,66,77]),np.array([60,85,60,68,55,60]))

array([ True,  True,  True,  True,  True,  True])

In [ ]:
#是